name       : shellcheck
version    : 0.4.5
release    : 1
source     :
    - https://github.com/koalaman/shellcheck/archive/v0.4.5.tar.gz : b9d34cd8aa88e2b278bd0df5009c18e84ff08a629b6e95c6b031236199232893
license    : GPL-3.0
component  : programming.tools
summary    : ShellCheck is a GPLv3 tool that gives warnings and suggestions for bash/sh shell scripts
description: |
    ShellCheck is a GPLv3 tool that gives warnings and suggestions for bash/sh shell scripts
builddeps  :
    - ghc
    - haskell-json
    - haskell-QuickCheck
    - haskell-regex-tdfa
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 ShellCheck-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/ShellCheck-$version.conf